source 'https://rubygems.org'

ruby '~> 3.0'

# Web Framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'  # For extensions
gem 'puma', '~> 7.2'
gem 'rackup', '~> 2.3'
gem 'rack', '>= 3.2.6'
gem 'rack-session', '>= 2.1.2'

# Data & Serialization
gem 'json', '~> 2.21'
gem 'csv', '~> 3.2'
gem 'pg', '~> 1.5', require: 'pg'
gem 'redis', '~> 5.2'

# Security & Authentication
gem 'bcrypt', '~> 3.1', '>= 3.1.22'
gem 'dotenv', '~> 2.8'  # Environment variable management
gem 'securerandom'

# Native Extensions
gem 'ffi', '~> 1.15'

# Testing
group :test do
  gem 'minitest', '~> 5.18'
  gem 'rack-test', '~> 2.1'
  gem 'mocha', '~> 2.0'  # For mocking
end

# Development
group :development do
  gem 'pry', '~> 0.14'  # REPL for debugging
  gem 'ruby-lsp', '~> 0.14'  # Language server
end

# Production monitoring (optional, can enable later)
# gem 'prometheus-client', '~> 4.0'
# gem 'sentry-ruby', '~> 5.0'
